In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import helper_utils

# This line ensures that your results are reproducible and consistent every time.
torch.manual_seed(42)

## Tensor shapes

In [4]:
# distance
distances = torch.tensor([[3.0], [7.0], [11.0], [15.0], [19.0], [23.0]])
print(distances)
print(distances.dtype)
print(distances.shape)  # torch.Size([6, 1])
print("------------")
simple_model = nn.Linear(in_features=1, out_features=1)
output = simple_model(distances)
print(output)  # tensor with shape torch.Size([6, 1])

tensor([[ 3.],
        [ 7.],
        [11.],
        [15.],
        [19.],
        [23.]])
torch.float32
torch.Size([6, 1])
------------
tensor([[ 0.2158],
        [-0.7213],
        [-1.6584],
        [-2.5955],
        [-3.5326],
        [-4.4697]], grad_fn=<AddmmBackward0>)


In [9]:
# distance, hour, weather
distances = torch.tensor([[7.0, 2.0, 0.0], [11.0, 3.0, 1.0], [15.0, 4.0, 1.0], [19.0, 5.0, 0.0], [23.0, 6.0, 0.0]])
print(distances.shape)  # torch.Size([5, 3])
simple_model = nn.Linear(in_features=3, out_features=1)
output = simple_model(distances)
print(output)  # tensor with shape torch.Size([5, 1])


torch.Size([5, 3])
tensor([[-1.7130],
        [-1.9893],
        [-2.7746],
        [-4.0689],
        [-4.8541]], grad_fn=<AddmmBackward0>)


## Creating Tensors

In [36]:
# Single value tensor
single_value_tensor = torch.tensor(7.0)
print(single_value_tensor.shape)  # torch.Size([])
print(single_value_tensor)  # tensor(7.)

torch.Size([])
tensor(7.)


In [37]:
single_value_tensor = single_value_tensor.unsqueeze(0)  # add a dimension
print(single_value_tensor.shape)  # torch.Size([1])
print(single_value_tensor)  # tensor([7.])

torch.Size([1])
tensor([7.])


In [13]:
random_tensor = torch.rand(2, 4)
print(random_tensor.shape)  # torch.Size([2, 4])
print(random_tensor)

torch.Size([2, 4])
tensor([[0.7886, 0.5895, 0.7539, 0.1952],
        [0.0050, 0.3068, 0.1165, 0.9103]])


In [15]:
my_distances = [[3.0], [7.0], [11.0], [15.0], [19.0], [23.0]]
tensor_distances = torch.tensor(my_distances)
print(tensor_distances.shape)  # torch.Size([6, 1])

torch.Size([6, 1])


In [16]:
import numpy as np
array_distances = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
tensor_distances = torch.from_numpy(array_distances)
print(tensor_distances.shape)  # torch.Size([5])

torch.Size([5])


## Tensor math 

In [21]:
distances_arr = [[3.0], [7.0], [12.0]]
distances = torch.tensor(distances_arr)
weights = torch.tensor(2.3)
bias = torch.tensor(8.0)
print(weights * distances + bias)  # tensor math operations

tensor([[14.9000],
        [24.1000],
        [35.6000]])


In [30]:
# print round 2 digits after decimal
print(f"{round(2.3 * 3.0 + 8.0, 2):.4f}")
print(f"{round(2.3 * 7.0 + 8.0, 2):.4f}")
print(f"{round(2.3 * 12.0 + 8.0, 2):.4f}")

14.9000
24.1000
35.6000


In [39]:
matrix_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix_tensor.shape)  # torch.Size([2, 3])
print(matrix_tensor)  # tensor([[1, 2, 3], [4, 5, 6]])
matrix_tensor_discounted = matrix_tensor * 0.9
print(matrix_tensor_discounted)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0.9000, 1.8000, 2.7000],
        [3.6000, 4.5000, 5.4000]])


### Exercises


In [20]:
# Sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

### START CODE HERE ###

# 1. Calculate total sales for Product B.
print("Sales data for Product B")
print(sales_data[1])
total_sales_product_b = sales_data[1].sum()
print(total_sales_product_b)

# 2. Find months where sales for Product C were > 130.
mask = sales_data[2] > 130
print(mask)
high_sales_mask_product_c = mask

# 3. Get sales for Feb and Mar for all products.

sales_feb_mar = sales_data[:, 1:3]
print(sales_feb_mar)


ORIGINAL SALES DATA:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------
Sales data for Product B
tensor([ 90.,  95., 105., 125.])
tensor(415.)
tensor([ True, False, False,  True])
tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])


In [23]:
# A batch of 4 grayscale images, each 3x3
image_batch = torch.rand(4, 3, 3)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

### START CODE HERE ###

# 1. Add a channel dimension at index 1.
image_batch_with_channel = image_batch.unsqueeze(1)
print("ORIGINAL BATCH SHAPE:", image_batch_with_channel.shape)
print("-" * 45)

# 2. Transpose the tensor to move the channel dimension to the end.
# image_batch_with_channel is [batch_size, channels, height, width]
# image_batch_with_channel is [batch_size, height, width, channels]
# Swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)
print("image_batch_transposed:", image_batch_transposed.shape)
print("-" * 45)

ORIGINAL BATCH SHAPE: torch.Size([4, 3, 3])
---------------------------------------------
ORIGINAL BATCH SHAPE: torch.Size([4, 1, 3, 3])
---------------------------------------------
image_batch_transposed: torch.Size([4, 3, 3, 1])
---------------------------------------------


In [25]:
# Sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("TEMPERATURE DATA: ", temperature)
print("TEMPERATURE DATA SHAPE: ", temperature.shape)
print("HUMIDITY DATA:    ", humidity)
print("HUMIDITY DATA SHAPE: ", humidity.shape)
print("-" * 45)

### START CODE HERE ###

# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = None

# 2. Create the weights tensor.
weights = None

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = None

# 4. Calculate the weighted average for each time step.
weighted_average = None

### END CODE HERE ###

print("\nCOMBINED DATA (2x5):\n\n", combined_data)
print("\nWEIGHTED DATA:\n\n", weighted_data)
print("\nWEIGHTED AVERAGE:", weighted_average)

TEMPERATURE DATA:  tensor([22.5000, 23.1000, 21.9000, 22.8000, 23.5000])
TEMPERATURE DATA SHAPE:  torch.Size([5])
HUMIDITY DATA:     tensor([55.2000, 56.4000, 54.8000, 57.1000, 56.8000])
HUMIDITY DATA SHAPE:  torch.Size([5])
---------------------------------------------

COMBINED DATA (2x5):

 None

WEIGHTED DATA:

 None

WEIGHTED AVERAGE: None
